function intvalue=qualbyte2int(qualbyte)
qualbyte_sign=bitshift(bitand(qualbyte(4),128),-7);
if qualbyte_sign==0    % sign is positive
    intvalue=bitor(bitshift(qualbyte(4),24),...
						bitor(bitshift(qualbyte(3),16),...
							bitor(bitshift(qualbyte(2),8),qualbyte(1) )...
							 )...
						 );						
else
    intvalue=bitor(bitshift(bitand(qualbyte(4),127),24),...
						bitor(bitshift(qualbyte(3),16),...
							bitor(bitshift(qualbyte(2),8),qualbyte(1) )...
							 )...
						 )-bitshift(1,31);	
end