% function intvalue=quarbyte2int(quarbyte)
% author: Ainray
% date: 2016/01/05
% bug-report: wwzhang0421@163.com
% introduction: covert four bytes into int32
%  input:
%         quarbyte, four-byte array
% output:
%         intvalue, return int32 value.
function intvalue=quarbyte2int(quarbyte) 
quarbyte_sign=bitshift(bitand(quarbyte(4),128),-7);
if quarbyte_sign==0    % sign is positive
    intvalue=bitor(bitshift(quarbyte(4),24),...
						bitor(bitshift(quarbyte(3),16),...
							bitor(bitshift(quarbyte(2),8),quarbyte(1) )...
							 )...
						 );	 					
else
    intvalue=bitor(bitshift(bitand(quarbyte(4),127),24),...
						bitor(bitshift(quarbyte(3),16),...
							bitor(bitshift(quarbyte(2),8),quarbyte(1) )...
							 )...
						 )-bitshift(1,31);	
end